In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('input/titanic_train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
X=df.iloc[:,[0,2,4,5,6,7,11]].values
y=df.iloc[:,1].values
X

array([[1, 3, 'male', ..., 1, 0, 'S'],
       [2, 1, 'female', ..., 1, 0, 'C'],
       [3, 3, 'female', ..., 0, 0, 'S'],
       ...,
       [889, 3, 'female', ..., 1, 2, 'S'],
       [890, 1, 'male', ..., 0, 0, 'C'],
       [891, 3, 'male', ..., 0, 0, 'Q']], dtype=object)

In [4]:
from sklearn.impute import SimpleImputer
impute=SimpleImputer(strategy='most_frequent')
impute.fit(X)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='most_frequent', verbose=0)

In [5]:
X=impute.transform(X)

In [6]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
X[:,2]=le1.fit_transform(X[:,2])
le2=LabelEncoder()
X[:,-1]=le2.fit_transform(X[:,-1])

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [8]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,random_state=0,test_size=0.2)

# Applying Random Forest Classifier

In [9]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=250,random_state=0)
classifier.fit(Xtrain,ytrain)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=250,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [10]:
acc_rfc=classifier.score(Xtest,ytest)*100
print(acc_rfc)

85.47486033519553


In [11]:
y_pred=classifier.predict(Xtest)

In [12]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(ytest,y_pred)
cm

array([[102,   8],
       [ 18,  51]], dtype=int64)

# Applying K-NN

In [13]:
from sklearn.neighbors import KNeighborsClassifier
classifier2=KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2)
classifier2.fit(Xtrain,ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [14]:
acc_knn=classifier2.score(Xtest,ytest)*100
print(acc_knn)

83.79888268156425


In [15]:
y_pred2=classifier2.predict(Xtest)

In [16]:
cm2=confusion_matrix(ytest,y_pred2)
cm2

array([[100,  10],
       [ 19,  50]], dtype=int64)

# Applying Decision Tree

In [17]:
from sklearn.tree import DecisionTreeClassifier
classifier3=DecisionTreeClassifier(max_depth=6)
classifier3.fit(Xtrain,ytrain)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=6, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [18]:
acc_dt=classifier3.score(Xtest,ytest)*100
print(acc_dt)

82.68156424581005


In [19]:
y_pred3=classifier3.predict(Xtest)

In [20]:
cm3=confusion_matrix(ytest,y_pred3)
cm3

array([[98, 12],
       [19, 50]], dtype=int64)

# Applying Naive Bayes

In [21]:
from sklearn.naive_bayes import GaussianNB
classifier4=GaussianNB()
classifier4.fit(Xtrain,ytrain)

GaussianNB(priors=None, var_smoothing=1e-09)

In [22]:
acc_nb=classifier4.score(Xtest,ytest)*100
print(acc_nb)

79.88826815642457


In [23]:
y_pred4=classifier4.predict(Xtest)

In [24]:
cm4=confusion_matrix(ytest,y_pred4)
cm4

array([[90, 20],
       [16, 53]], dtype=int64)

# Applying SVC

In [25]:
from sklearn.svm import SVC
classifier5=SVC(kernel='rbf',random_state=0)
classifier5.fit(Xtrain,ytrain)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [26]:
acc_svc=classifier5.score(Xtest,ytest)*100
print(acc_svc)

82.12290502793296


In [27]:
y_pred5=classifier5.predict(Xtest)

In [28]:
cm5=confusion_matrix(ytest,y_pred5)
cm5

array([[98, 12],
       [20, 49]], dtype=int64)

# Applying Logistic Classification

In [29]:
from sklearn.linear_model import LogisticRegression
classifier6=LogisticRegression()
classifier6.fit(Xtrain,ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [30]:
acc_lc=classifier6.score(Xtest,ytest)*100
print(acc_lc)

81.00558659217877


In [31]:
y_pred6=classifier6.predict(Xtest)

In [32]:
cm6=confusion_matrix(ytest,y_pred6)

In [33]:
cm6

array([[91, 19],
       [15, 54]], dtype=int64)

# Applying Perceptron

In [35]:
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
perceptron = Perceptron()
perceptron.fit(Xtrain, ytrain)
y_pred8 = perceptron.predict(Xtest)
acc_perceptron = round(accuracy_score(y_pred8, ytest) * 100, 2)
print(acc_perceptron)

77.65


C:\Users\Mrigank Singh\Anaconda3\envs\digiml\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [36]:
y_pred8=perceptron.predict(Xtest)
cm8=confusion_matrix(ytest,y_pred8)
print(cm8)

[[86 24]
 [16 53]]


# Applying Stochastic Gradient Descent

In [37]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
sgd = SGDClassifier()
sgd.fit(Xtrain, ytrain)
y_pred10 = sgd.predict(Xtest)
acc_sgd = round(accuracy_score(y_pred, ytest) * 100, 2)
print(acc_sgd)

85.47


C:\Users\Mrigank Singh\Anaconda3\envs\digiml\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [38]:
y_pred9=perceptron.predict(Xtest)
cm9=confusion_matrix(ytest,y_pred9)
print(cm9)

[[86 24]
 [16 53]]


In [39]:
models = pd.DataFrame({
    'Model': ['Random Forest Classifier', 'KNN', 'Decision Tree', 
               'Naive Bayes','Linear SVC', 'Logistic Classification', 'Perceptron', 
              'Stochastic Gradient Descent'],
    'Score': [acc_rfc, acc_knn, acc_dt, 
              acc_nb, acc_svc, acc_lc,acc_perceptron, acc_sgd]})
models.sort_values(by='Score', ascending=False)


Model      Score
0     Random Forest Classifier  85.474860
7  Stochastic Gradient Descent  85.470000
1                          KNN  83.798883
2                Decision Tree  82.681564
4                   Linear SVC  82.122905
5      Logistic Classification  81.005587
3                  Naive Bayes  79.888268
6                   Perceptron  77.650000

In [40]:
from sklearn.model_selection import cross_val_score
rf = RandomForestClassifier(n_estimators=250)
scores = cross_val_score(rf, Xtrain, ytrain, cv=10, scoring = "accuracy")
print("Scores:", scores)
print("Mean:", scores.mean())
print("Standard Deviation:", scores.std())

Scores: [0.72222222 0.73611111 0.81944444 0.85915493 0.78873239 0.76056338
 0.78873239 0.8028169  0.87323944 0.78571429]
Mean: 0.7936731500111781
Standard Deviation: 0.045818632820698216


In [41]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
predictions = cross_val_predict(rf, Xtrain, ytrain, cv=3)
confusion_matrix(ytrain, predictions)

array([[377,  62],
       [ 89, 184]], dtype=int64)

In [42]:
from sklearn.metrics import precision_score, recall_score

print("Precision:", precision_score(ytrain, predictions))
print("Recall:",recall_score(ytrain, predictions))

Precision: 0.7479674796747967
Recall: 0.673992673992674


0    85.474860
1    83.798883
2    82.681564
3    79.888268
4    82.122905
5    81.005587
6    77.650000
7    85.470000
Name: Score, dtype: float64

In [4]:
import pandas as pd
for i in range(10):
    model1=pd.DataFrame({
    'Numbers':[i]
    })

In [5]:
model1

Numbers
0        9